name: Automation test run
on:
  repository_dispatch:
jobs:
  build:
    name: Automation run
    runs-on: ubuntu-latest
    steps:
      - name: Do Something
      - run: echo Doing Something...
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
